# Generated by Django 4.2.6 on 2023-10-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.IntegerField()),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpSal', models.IntegerField()),
                ('EmpAdd', models.CharField(max_length=100)),
            ],
        ),
    ]
