# Generated by Django 4.2.6 on 2023-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('JobTitle', models.CharField(blank=True, max_length=30)),
                ('BioData', models.TextField(blank=True)),
            ],
        ),
    ]
