# Generated by Django 4.2.6 on 2023-11-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Sala', models.IntegerField()),
                ('Loca', models.CharField(max_length=100)),
                ('Posi', models.CharField(max_length=100)),
            ],
        ),
    ]
