# Generated by Django 4.2.6 on 2023-12-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalCity',
            fields=[
                ('cname', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebApp.state')),
            ],
        ),
    ]
